name: "hello"
# Controls when the action will run. Triggers the workflow on push done to the main1 branch
on: 
  push:
    branches:
      - main1

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: "Print Hello world"
        run: echo "Hello World"
      